name: model-quality

on:
  push:
    branches: ["main", "feature"]
  
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{secrets.GITHUB_TOKEN}}
        run: |  
          pip install -r requirements.txt
          python train.py
          cat metrics.json
      - name: Comment
        uses: JoseThen/comment-pr@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          file_path: ./metrics.json
        
