name: Cleanup Workflow Runs

on:
  workflow_dispatch:

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old workflow runs
        run: echo Hello world
