name: Cleanup Workflow Runs

on:
  workflow_dispatch:

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old workflow runs
        uses: InfraWay/delete-workflow-runs@v2.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 1
