name: train_evaluate

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write



jobs:
  train-report-more:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Python-setup
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.11

      - name: Dependencies
        run: pip install -r requirements.txt

      - name: DVC Setup
        uses: iterative/setup-dvc@v1
      - name: DVC Run
        run: dvc repro

      - name: Write report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ![](./confusion_matrix.png) > report.md
          dvc metrics show --md >> report.md
          git fetch --prune
          dvc metrics diff --md main >> report.md
          echo hello

      - name: Comment
        uses: JoseThen/comment-pr@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          file_path: ./report.md


      
