name: train_evaluate

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write # ⬅️ Потрібно для CML, щоб завантажувати зображення
  pull-requests: write

jobs:
  train-report-more:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Python-setup
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.11

      - name: Dependencies
        run: pip install -r requirements.txt

      - name: DVC Setup
        uses: iterative/setup-dvc@v1
        
      # === КРОК 1: ВСТАНОВЛЕННЯ CML ===
      - name: Setup Node
        uses: actions/setup-node@v4 # ⬅️ Потрібен для CML
        with:
          node-version: '20' 

      - name: Install CML CLI
        # Встановлюємо CML через NPM (це найнадійніший спосіб)
        run: npm install -g cml
      # =================================

      - name: DVC Run
        run: dvc repro # Тут генеруються metrics.json та predictions.csv

      - name: Write report and create plot
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 1. Генерація звіту Markdown
          echo "## 📊 ML-Пайплайн Звіт" > report.md
          dvc metrics show --md >> report.md
          
          git fetch --prune
          dvc metrics diff --md main >> report.md

          # 2. ГЕНЕРУЄМО ЗОБРАЖЕННЯ МАТРИЦІ ПЛУТАНИНИ (SVG)
          # DVC генерує SVG на основі конфігурації 'plots' у dvc.yaml
          dvc plots show --title "Confusion Matrix" --target predictions.csv -o confusion_matrix.svg
          
          # 3. ДОДАЄМО ЗОБРАЖЕННЯ ДО ЗВІТУ
          # CML-команда 'cml pr write' може приймати текст та зображення
          echo "### Матриця Плутанини" >> report.md
          echo "![](./confusion_matrix.svg)" >> report.md # Посилаємося на SVG-файл
          
          # 4. ПУБЛІКУЄМО ЗВІТ ТА ЗОБРАЖЕННЯ ЧЕРЕЗ CML
          # CML автоматично завантажує локальні зображення (SVG/PNG) на GitHub і вставляє їх у коментар.
          cml pr write report.md
