name: train_evaluate

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write



jobs:
  train-report-more:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Python-setup
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.11

      - name: Dependencies
        run: pip install -r requirements.txt

      - name: DVC Setup
        uses: iterative/setup-dvc@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install CML CLI
        run: npm install -g cml

      - name: DVC Run
        run: dvc repro

      - name: Write report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc metrics show --md > report.md

      - name: Comment
        uses: JoseThen/comment-pr@v1.2.0
        with:
          comment: 'This PR is the bees knees!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
